// <auto-generated />
using System;
using ASAP_Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASAP_Context.Migrations
{
    [DbContext(typeof(ASAPDBcontext))]
<<<<<<<< HEAD:ASAP-Context/Migrations/20240407105833_Initial.Designer.cs
    [Migration("20240407105833_Initial")]
    partial class Initial
========
    [Migration("20240408114153_stockProperty")]
    partial class stockProperty
>>>>>>>> 2a31de161e3c0a708fb3e625fb52b87a640a59de:ASAP-Context/Migrations/20240408114153_stockProperty.Designer.cs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ASAP_Models.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ClientId");

                    b.ToTable("clients");
                });

            modelBuilder.Entity("ASAP_Models.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
<<<<<<<< HEAD:ASAP-Context/Migrations/20240407105833_Initial.Designer.cs

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");
========
>>>>>>>> 2a31de161e3c0a708fb3e625fb52b87a640a59de:ASAP-Context/Migrations/20240408114153_stockProperty.Designer.cs

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("split_from")
                        .HasColumnType("int");

                    b.Property<int>("split_to")
                        .HasColumnType("int");

                    b.Property<string>("ticker")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

<<<<<<<< HEAD:ASAP-Context/Migrations/20240407105833_Initial.Designer.cs
                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

========
>>>>>>>> 2a31de161e3c0a708fb3e625fb52b87a640a59de:ASAP-Context/Migrations/20240408114153_stockProperty.Designer.cs
                    b.HasKey("Id");

                    b.ToTable("stocks");
                });
#pragma warning restore 612, 618
        }
    }
}
